### ISSUE TITLE
Hide material ui table of content

### ISSUE THREAD

**Issue by sassouiabd** [CoinK0in/mkdocs-encryptcontent-plugin#21]
Hello,
Is it possible to hide  the table of content from [material ui theme](https://github.com/squidfunk/mkdocs-material) when the file is not unlocked yet ?

![Capture](https://user-images.githubusercontent.com/51038094/159157538-27254d43-d10b-495e-9f24-ff057330c0aa.JPG)

**Comment by CoinK0in** [comment]
Hey, it's possible as described in [example #2](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#how-to-use-it-exploding_head--examples) of the encrypt something feature.
You have to edit your theme templates to add a tag. 
Tag that you had to use with the same name in the configuration in order to encrypt the content table.

**Comment by sassouiabd** [comment]
@CoinK0in that works ! Thank you so much 🥇
