### ISSUE TITLE
Incorrect internal ToC when using plugin

### ISSUE THREAD

**Issue by martinbira** [CoinK0in/mkdocs-encryptcontent-plugin#8]
## Description

Not sure if this is 100% the plugin or as a combination of using the plugin with Material for MkDocs, but the internal ToC includes the page title when using the plugin.

### Expected behavior

The first post of the internal ToC is the first section of the page, not the page title.

### Actual behavior

The first post of the internal ToC is the page title.

### Steps to reproduce the bug

1. Create a page with a page title and a few sections and view it with MkDocs.
2. Enable the plugin and set a password for the page. View again

**No password:**
![4-correct-behaviour-logged-in](https://user-images.githubusercontent.com/22232681/90251687-7a55bf80-de3e-11ea-9a92-b8e5e079d253.png)

**Using password:**
![3-incorrect-behaviour-logged-in](https://user-images.githubusercontent.com/22232681/90251700-7e81dd00-de3e-11ea-9105-e3c3e56c55c4.png)

### Package versions

* Python: `3.8.3`
* MkDocs: `1.1.2`
* Material: `5.5.3`
* mkdocs-encryptcontent-plugin: `0.0.3`

**Comment by CoinK0in** [comment]
I reproduced this 'problem' when installed a Material theme and I try to fix it.

I use:
     Python: 3.8.2
     MkDocs: 1.1.2
     Material: 5.5.7
     mkdocs-encryptcontent-plugin: 0.0.8

The ToC always have the default page title as first elements, except when the title is not on markdown page.
I think it's a plugins call order problem when the page is generated. 
But I am not sure of anything for the moment, I will give you a feedback on this ASAP

**Comment by CoinK0in** [comment]
The problem come from the way of the Material theme uses the page content to identify the ToC hierarchy.
In the template `toc.html`, Material search `"\x3ch1 id=" in page.content` to reduce hierarchy level at child items.
But the encryptcontent plugin converts the content of the page to a set of cipher texts starting with `<div id="mkdocs-encrypted-content" style="display:none">` which no longer matches the condition ...

So, I cannot delete the first ToC element when I encrypt the page because it depends very much on the theme used. 
The best solution seems to be to add a new condition in the theme's `toc.html` template.
With the additional condition `or '\x3cdiv id="mkdocs-encrypted-content"' in page.content`, ToC hierarchy is now reduced correctly on encrypted pages.

The final version of the template, should look like this :
```jinja
{% if toc | first is defined and "\x3ch1 id=" in page.content or '\x3cdiv id="mkdocs-encrypted-content"' in page.content %}
    {% set toc = (toc | first).children %}
{% endif %}
```
